const PRIME_RUNTIME_GLOBAL_NAMES = [
	"$",
	"Bun",
	"fs",
	"os",
	"path",
	"util",
	"require",
	"sh",
	"installPackage",
	"hostRequest",
	"rlm",
	"__primeDisplay",
	"__primeHostRequest",
] as const;

const BUN_ONLY_GLOBAL_NAMES = [
	"AsyncDisposableStack",
	"BuildError",
	"BuildMessage",
	"CloseEvent",
	"DisposableStack",
	"ErrorEvent",
	"Float16Array",
	"HTMLRewriter",
	"PerformanceServerTiming",
	"PerformanceTiming",
	"ResolveError",
	"ResolveMessage",
	"ShadowRealm",
	"SuppressedError",
	"URLPattern",
	"Worker",
	"addEventListener",
	"alert",
	"confirm",
	"dispatchEvent",
	"ffi",
	"jsc",
	"onerror",
	"onmessage",
	"postMessage",
	"prompt",
	"removeEventListener",
	"reportError",
	"self",
	"sqlite",
] as const;

export const BUN_RUNTIME_GLOBAL_NAMES: ReadonlySet<string> = new Set([
	...Object.getOwnPropertyNames(globalThis),
	...BUN_ONLY_GLOBAL_NAMES,
	...PRIME_RUNTIME_GLOBAL_NAMES,
]);
